### PR TITLE
added leading Prov + Fixes to warp + Cleanup

### PR DESCRIPTION
**Pull request by tati-micheletti**

### CODE REVIEW

**Comment by achubaty** [comment]
Since we need to recreate the climate data sets from ClimateNA to ensure they are all on the same resolution etc., and we no longer require buffers for each province now that the study area is used to determine which data to download (rather than the user specifying e.g., "NT"), I don't see the need for leadingArea.

**Comment by eliotmcintire** [comment]
When I was testing with "changing the order", it looked like there was no effect because the underlying data was the same (e.g., the northern buffer of AB was the same values as the southern buffer of NT). Is this true?  In other words, since the data are all coming from a single source (ClimateNA), won't the pixel values be the same *if they have non-NA data* regardless of which jurisdiction they are from?

If this is the case, then I agree with Alex and the original "pre-PR" should be fine, i.e., no ordering, just take them as they are.

NOTING: @ianmseddy 's point that we need to make sure the zeros (real values) and NAs (no values) are not being confounded, but that is a different issue.

**Comment by tati-micheletti** [comment]
There is an effect, but you don't see it unless the original Dem used for
climateNA has a different resolution (which is the case currently for Yukon
and BC). In this case, the last raster is the one being put on top.

**Comment by tati-micheletti** [comment]
Maybe we can get rid of the order once the data is re-downloaded with the same resolution. But I still think it might be useful in other cases (ie. new data) and it doesn't hurt being there.

**Comment by eliotmcintire** [comment]
If this is true, then there needs to be more than just `leadingArea` ... it should be "order" or "sequence". If the `studyArea` spans 2 areas (i.e., "Mountain Caribou range" which is BC and YT and NT ... and lets say that AB would be in the buffer)... we would want `"order = c("AB", "NT", "BC", "YT")` or something like that, with the `BC` and `YT` order being not important (ie., YT or BC could be last)

**Comment by tati-micheletti** [comment]
This is true, and I agree that the full order could be implemented. Sorry I
didn't have time for it, but please feel free to change it.

**Pull request merged**
